aracSecimi/Models/Siniflar/Iletisim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace aracSecimi.Models
{
    public class Iletisim
    {
        [Key]
        public int Id { get; set; }
        public string AdSoyad {get; set;}
        public string Mail {get; set;}
        public string Konu {get; set;}
        public string Mesaj {get; set;}

}
}

aracSecimi/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using aracSecimi.Models;
using aracSecimi.Models.Siniflar;

namespace aracSecimi.Controllers
{
    public class IletisimController : Controller 
    {
        Context c = new Context();

        // GET: Iletisim
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Ekle(Iletisim i )
        {
            c.Iletisims.Add(i);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

aracSecimi/Views/Iletisim/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div>


    <br />
    <div class="row px-xl-5">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 mb-5" style="border-radius:10px; padding:40px; box-shadow:2px 2px 10px #ccc">


            <div class="text-center mb-4">
                <h2 class="section-title px-5"><span class="px-2">Bize Ulaşın </span></h2>
            </div>

            <div class="contact-form">
                <div id="success"></div>


                @using (Html.BeginForm("Ekle", "Iletisim", FormMethod.Post))
                {
                    <div class="control-group">
                        <input type="text" class="form-control" name="AdSoyad" id="AdSoyad" autocomplete="off" placeholder="Adınız Soyadınız"
                               required="required" data-validation-required-message="Please enter your name" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="email" class="form-control" id="Mail" autocomplete="off" placeholder="Mail Adresiniz"
                               required="required" name="Mail" data-validation-required-message="Please enter your email" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="text" name="Konu" class="form-control" id="Konu" placeholder="Konu"
                               required="required" autocomplete="off" data-validation-required-message="Please enter a subject" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <textarea class="form-control" name="Mesaj" rows="6" id="Mesaj" placeholder="Mesajınız"
                                  required="required"
                                  data-validation-required-message="Please enter your message"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" style="border-radius:5px" type="submit" id="sendMessageButton"
                            onclick="Gonder();" >
                            Gönder
                        </button>
                    </div>

                }


            </div>
        </div>
        <div class="col-lg-2"></div>

    </div>


</div>



<script>
    function Gonder() {
        var adsoyad = document.getElementById("AdSoyad");
        var mail = document.getElementById("Mail");
        var konu = document.getElementById("Konu");
        var mesaj = document.getElementById("Mesaj");
        



        if (adsoyad.value != "" && mail.value != "" && konu.value != "" && mesaj.value != "") {

            alert("İşleminiz başarılı bir şekilde gönderildi.");


        }


    }
</script>
